#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StackExchange.Exceptional.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Pages\Master.cshtml"
    using StackExchange.Exceptional;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Master : RazorPageBase
    {
#line hidden

        #line 6 "..\..\Pages\Master.cshtml"

    public string PageTitle { get; set; }
    public Error Error { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("<!DOCTYPE html>\r\n");




            
            #line 4 "..\..\Pages\Master.cshtml"
   var log = ErrorStore.Default; 

            
            #line default
            #line hidden

WriteLiteral("\r\n<html>\r\n    <head>\r\n        <title>");


            
            #line 12 "..\..\Pages\Master.cshtml"
          Write(PageTitle);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n        <link rel=\"stylesheet\" type=\"text/css\" href=\"");


            
            #line 13 "..\..\Pages\Master.cshtml"
                                                Write(Url("css"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");


            
            #line 14 "..\..\Pages\Master.cshtml"
         foreach(var css in ErrorStore.CSSIncludes)
        {

            
            #line default
            #line hidden
WriteLiteral("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");


            
            #line 16 "..\..\Pages\Master.cshtml"
                                                Write(css);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");


            
            #line 17 "..\..\Pages\Master.cshtml"
        }

            
            #line default
            #line hidden

            
            #line 18 "..\..\Pages\Master.cshtml"
         if(Error != null)
        {

            
            #line default
            #line hidden
WriteLiteral("        <script>var Exception = ");


            
            #line 20 "..\..\Pages\Master.cshtml"
                           Write(Html(Error.ToDetailedJson()));

            
            #line default
            #line hidden
WriteLiteral(";</script>\r\n");


            
            #line 21 "..\..\Pages\Master.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <!--[if lt IE 9]><script src=\"");


            
            #line 22 "..\..\Pages\Master.cshtml"
                                 Write(Url("html5shiv"));

            
            #line default
            #line hidden
WriteLiteral("\"></script><![endif]-->\r\n        <script src=\"");


            
            #line 23 "..\..\Pages\Master.cshtml"
                Write(ErrorStore.jQueryURL);

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n        <script src=\"");


            
            #line 24 "..\..\Pages\Master.cshtml"
                Write(Url("js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n        <script>var baseUrl = \'");


            
            #line 25 "..\..\Pages\Master.cshtml"
                          Write(Url(""));

            
            #line default
            #line hidden
WriteLiteral("\';</script>\r\n");


            
            #line 26 "..\..\Pages\Master.cshtml"
         foreach(var js in ErrorStore.JSIncludes)
        {

            
            #line default
            #line hidden
WriteLiteral("        <script src=\"");


            
            #line 28 "..\..\Pages\Master.cshtml"
                Write(js);

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n");


            
            #line 29 "..\..\Pages\Master.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </head>\r\n    <body>\r\n        <div id=\"top-header\" class=\"");


            
            #line 32 "..\..\Pages\Master.cshtml"
                                Write(ErrorStore.Default.InFailureMode ? "failure" : "");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            <div class=\"top-label\">Exceptions Log: ");


            
            #line 33 "..\..\Pages\Master.cshtml"
                                              Write(Settings.Current.ApplicationName);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </div>\r\n        <section id=\"content\">\r\n        ");


            
            #line 36 "..\..\Pages\Master.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </section>\r\n        <footer>\r\n            <div class=\"version-info\">\r\n " +
"               Exceptional ");


            
            #line 40 "..\..\Pages\Master.cshtml"
                       Write(System.Reflection.Assembly.GetExecutingAssembly().GetName().Version);

            
            #line default
            #line hidden
WriteLiteral("<br/>\r\n                ");


            
            #line 41 "..\..\Pages\Master.cshtml"
           Write(log.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div class=\"server-time\">Server time is ");


            
            #line 43 "..\..\Pages\Master.cshtml"
                                               Write(DateTime.Now);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </footer>\r\n    </body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
